### ISSUE TITLE
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by aCID3D** [ChistiyKot/gobot-nw#1]
hi i dont understand it can u explain that where i have to copie files or install what ?

**Comment by ChistiyKot** [comment]
Hello, thank you for you issue. You should install mingw for windows (as in README) and do some post-installation steps like adding full path to bin files to your system's %PATH% environment variable. Here you can find some details about it https://www.geeksforgeeks.org/installing-mingw-tools-for-c-c-and-changing-environment-variable/
